export default {
    cates:[
    {
        id:'1',
        time:'1 hour',
        image:"https://image.thanhnien.vn/w2048/Uploaded/2014/Pictures20118/VienAn/7KyQuanThienNhienTheGioi/halong3-Wonder.jpg",
        name:"Vịnh Hạ Long",
        detail:"Vịnh Hạ Long nằm ở tỉnh Quảng Ninh, Việt Nam. Vịnh có bờ biển dài 120 km, diện tích 1.553 km2, với 1.969 hòn đảo lớn nhỏ, nhiều hồ bên trong những hang động đá vôi khổng lồ.",
        post:"Vùng vịnh Hạ Long được UNESCO công nhận là di sản thiên nhiên thế giới có diện tích 434 km², như một hình tam giác với ba đỉnh là đảo Đầu Gỗ (phía tây), hồ Ba Hầm (phía nam) và đảo Cống Tây (phía đông), bao gồm 775 đảo với nhiều hang động, bãi tắm.",
        noidung:"Vịnh Hạ Long trở thành một trong 7 Kỳ quan Thiên nhiên mới của thế giới,được UNESCO hai lần công nhận là di sản thiên nhiên thế giới vào các ngày 17/12/1994 và 02/12/2000. Danh hiệu UNESCO gồm danh sách các di sản thế giới, khu dự trữ sinh quyển thế giới, di sản tư liệu thế giới, công viên địa chất toàn cầu, di sản văn hóa phi vật thể của nhân loại.... Trong hệ thống các danh hiệu của UNESCO, di sản thế giới là danh hiệu danh giá nhất và lâu đời nhất.  Nằm trong danh sách N7W sơ bộ được liệt kê theo thứ tự bảng chữ cái: Rừng Amazon (Nam Mỹ, nằm trên lãnh thổ Bolivia, Brazil, Colombia, Ecuador, Guiana, Guyana, Surianme, Venezuela); Vịnh Hạ Long (Việt Nam), Thác nước Iguazu (Argentina, Brazil), Đảo Jeju (Hàn Quốc), Đảo Komodo (Indonesia), Dòng sông ngầm Puerto Princesa (Philippines) và Núi Bàn (Nam Phi).Vịnh Hạ Long được công nhận về giá trị địa chất, địa mạo và vẻ đẹp vượt qua hơn 400 kỳ quan từ hơn 200 quốc gia và vùng lãnh thổ, lọt vào danh sách 28 ứng viên để lựa chọn ra 7 kỳ quan được New 7 Wonders (N7W) công bố.",
        tacgia:"khangle",
        bgimage:"https://halongbay.com.vn/Data/images/slide/slide5.jpg",
        img1:"https://cdn.pixabay.com/photo/2020/01/30/20/18/nature-4806451__340.jpg",
        img2:"https://cdn.pixabay.com/photo/2017/05/21/09/24/vietnam-2330843__480.jpg",
        img3:"https://cdn.pixabay.com/photo/2020/02/10/18/52/nature-4837410__340.jpg",
        img4:"https://cdn.pixabay.com/photo/2014/03/17/17/57/halong-289278__480.jpg",

        
        
    },
    {
        id:'2',
        time:'3 hour',
        image:"https://image.thanhnien.vn/w2048/Uploaded/2014/Pictures20118/VienAn/7KyQuanThienNhienTheGioi/Amazon1.jpg",
        name:"Amazon",
        detail:"Amazon là rừng mưa nhiệt đới, có diện tích 7 triệu km2, trong đó, rừng già chiếm 5,5 triệu km2. Khu rừng trải rộng trên 9 quốc gia và vùng lãnh thổ của Nam Mỹ (Bolivia, Brazil, Colombia, Ecuador, Guiana, Guyana, Surianme, Venezuela).",
        post:"Diện tích rừng Amazon chiếm hơn ½ trong tổng diện tích các khu rừng nhiệt đới trên toàn hành tinh, với hệ đa dạng sinh học lớn nhất thế giới. Bên cạnh đó, con sông Amazon cũng là sông lớn nhất thế giới, với tổng lưu lượng nước lớn hơn 10 con sông lớn tiếp theo trên thế giới cộng lại.",
        noidung:"Với diện tích 5,5 triệu km 2 , rừng mưa nhiệt đới Amazon là khu rừng lớn nhất thế giới, có độ bao phủ kéo dài gần hết lưu vực sông Amazon. 60% diện tích rừng nằm trong lãnh thổ đất nước Brazil, phần còn lại thuộc Peru, Colombia, Venezuela, Ecuador, Bolivia, Guyana, Surinam và Guyana thuộc Pháp.Với diện tích 5,5 triệu km 2 , rừng mưa nhiệt đới Amazon là khu rừng lớn nhất thế giới, có độ bao phủ kéo dài gần hết lưu vực sông Amazon. 60% diện tích rừng nằm trong lãnh thổ đất nước Brazil, phần còn lại thuộc Peru, Colombia, Venezuela, Ecuador, Bolivia, Guyana, Surinam và Guyana thuộc Pháp.Tuy nhiên, khu rừng nhiều năm trở lại đây đang bị hủy hoại do nạn chặt phá rừng và nạn săn bắt động vật quý hiếm. Theo thống kê, trong 50 năm vừa qua, diện tích rừng đã bị giảm đi khoảng 17%.Rừng Amazon còn được xem là một nơi bí ẩn ngay cả với giới khoa học. Người ta tin rằng rừng đã xuất hiện từ khoảng 10.000 năm trước. Họ còn tin rằng rừng là một kế hoạch lỗi của các bộ tộc sống tại đây khi họ thử nghiệm trồng trọt nhưng lại không thể kiểm soát được tốt độ phát triển của các loài cây, do đó mới sinh ra rừng Amazon như bây giờ.",
        tacgia:"báo thanh niên",
        bgimage:"https://i1-dulich.vnecdn.net/2018/04/17/Peru-Amazon-0137-5245-1523964060.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=5ftCZYi4YVUF8WsdGCdhzg",
        img1:"https://cdn.pixabay.com/photo/2015/09/26/21/33/suspension-bridge-959853__340.jpg",
        img2:"https://cdn.pixabay.com/photo/2020/01/16/01/01/amazon-4769367__480.jpg",
        img3:"https://cdn.pixabay.com/photo/2017/09/16/19/34/parrot-2756491__340.jpg",
        img4:"https://cdn.pixabay.com/photo/2017/09/16/19/33/parrot-2756488__480.jpg",
    },
    {
        id:'3',
        time:'5 hour',
        image:"https://image.thanhnien.vn/w2048/Uploaded/2014/Pictures20118/VienAn/7KyQuanThienNhienTheGioi/Thac-Iguazu.jpg",
        name:"Thác nước Iguazu",
        detail:"Thác nước Iguazu là một trong những thác nước lớn nhất thế giới, bao gồm 275 thác nhỏ cùng tạo nên một quần thể thác lớn Iguazu.",
        post:" Thác nước Iguazu là một trong những thác nước lớn nhất thế giới, bao gồm 275 thác nhỏ cùng tạo nên một quần thể thác lớn Iguazu. Đỉnh cao nhất của thác cao 80m. Thác nằm giữa Brazil và Argentina, được bao quanh bởi hai vườn quốc gia của hai nước này.",
        noidung:"Có phải chăng bạn đã đi qua rất nhiều thác nước nổi tiếng trên thế giới và luôn được đón nhận không khí tươi mát của dòng chảy thiên nhiên, đem lại trong bạn những cảm nhận riêng biệt khó quên. Vậy bạn đã bao giờ biết đến một dòng thác nổi tiếng ở Nam Mỹ, nơi những dòng nước vẫn âm thầm chảy giữa cánh rừng nhiệt đới từ lâu đã khiến mỗi du khách đến đây đều phải ngẩn ngơ ngước nhìn. Và sau mỗi cơn mưa, cầu vồng hiện lên trên dòng thác giống như chiếc cổng nhiệm màu dẫn lối vào khu vườn cổ tích xa xưa.Nằm giữa biên giới Brazil và Argentina, thác Iguazu được cả hai quốc gia ra sức bảo vệ và thu hút hàng trăm nghìn du khách đến đây tham quan và nghỉ dưỡng. Thác Iguazu được người Tây Ban Nha phát hiện ra lần đầu tiên vào năm 1541. Tên thác gọi theo tiếng bản địa Guarani gồm hai âm I là lớn và Guazu là nước có nghĩa là “nước lớn”. Thác nước hình thành từ sự phun trào của núi lửa, tạo nên khe nứt trong lòng đất. Dòng dung nham rực lửa ngày trước bây giờ đã biến thành những dải nước nối nhau chảy xuống dòng sông xanh mát.Một truyền thuyết của những thổ dân da đỏ lại cho rằng sự hình thành của thác Iguazu là kết quả của sự ghen tuông của một vị thần. Chuyện kể rằng, có một thuỷ thần đã lên kế hoạch kết hôn với một thiếu nữ xinh đẹp ở trần gian tên là Naipi con gái của tộc trưởng ở đây. Nhưng cô gái không chấp nhận và bỏ trốn cùng người yêu của mình là chiến binh Taroba trên chiếc thuyền độc mộc. Trong cơn phẫn nộ, vị thần đã tạo ra một dòng thác khổng lồ để nhấn chìm chiếc thuyền của họ. Cũng từ đó, trên dòng sông Iguazu đã xuất hiện dòng thác lớn tồn tại cho đến bây giờ.",
        tacgia:"vyctravel",
        bgimage:"http://vyctravel.com/libs/upload/ckfinder/images/NamMy/Brazil%20Argentina/66185024_6143447952801_8688850347411636224_n_800x534.jpg",
        img1:"https://cdn.pixabay.com/photo/2013/11/29/21/09/foz-do-iguacu-221275__340.jpg",
        img2:"https://cdn.pixabay.com/photo/2018/07/08/14/56/iguassu-3524054__340.jpg",
        img3:"https://cdn.pixabay.com/photo/2020/04/13/22/20/waterfall-5040212__480.jpg",
        img4:"https://cdn.pixabay.com/photo/2016/03/03/12/40/iguazu-1234122__480.jpg",
    },
    {
        id:'4',
        time:'3 hour',
        image:"https://image.thanhnien.vn/w2048/Uploaded/2014/Pictures20118/VienAn/7KyQuanThienNhienTheGioi/DaoJeJu.jpg",
        name:"Jeju  ",
        detail:" Jeju là một hòn đảo núi lửa ở Hàn Quốc. Đây là đảo lớn nhất và là tỉnh nhỏ nhất ở Hàn Quốc. Hòn đảo có diện tích bề mặt 1.846 km2.",
        post:"Jeju là một hòn đảo núi lửa ở Hàn Quốc. Đây là đảo lớn nhất và là tỉnh nhỏ nhất ở Hàn Quốc. Hòn đảo có diện tích bề mặt 1.846 km2. Tâm điểm của đảo Jeju là ngọn núi cao nhất Hàn Quốc Hallasan (đã ngưng hoạt động, cao 1.950m so với mặt nước biển). Xung quanh Hallasan còn có 360 núi lửa “vệ tinh”.",
        noidung:"Được mệnh danh là hòn đảo của hòa bình, hay đảo tình yêu, phim trường của rất nhiều bộ phim nổi tiếng làm say lòng khán giả quốc tế. Đảo Jeju khiến khách du lịch say đắm bởi nét đẹp bình lặng, hoang sơ nhưng không kém phần quyến rũ của nó. Nơi đây có cảnh sắc thiên nhiên rất đẹp và thơ mộng với nhiều điểm du lịch thú vị mà bạn không thể bỏ lỡ. Đảo cũng là một trong những điểm đến lý tưởng của du khách trong bất kỳ thời điểm nào trong năm. Đến đây một lần, bạn sẽ phải cảm thán trước sự kỳ diệu của tạo hóa! Đảo Jeju - điểm du lịch Hàn Quốc lý tưởng, để được tận hưởng cảm giác mát mẻ của biển xanh, những bãi tắm đẹp, được gần gũi thiên nhiên và thưởng thức những món ăn nổi tiếng nơi đây luôn là trải nghiệm tuyệt vời và ý nghĩa đối với mỗi du khách.Jeju là hòn đảo lớn nhất của Hàn Quốc, có chiều dài là 41km chiều rộng là 73km. Là nơi có khí hậu tuyệt vời nhất của Hàn Quốc, thời tiết ôn hòa mát mẻ quanh năm, thời điểm nóng nhất trong năm nhiệt độ cũng chỉ tới 33 độ C. Cảnh quan nơi đây khiến không chỉ người dân mà du khách quốc tế cũng không khỏi ngất ngây. Thiên nhiên đẹp với các thác nước tự nhiên hùng vĩ, các bãi biển trắng trải dài, nước biển trong xanh cùng rất nhiều các điểm tham quan tuyệt đẹp. Thời điểm tuyệt vời nhất để đến du lịch đảo Jeju Hàn Quốc là từ tháng 4 đến tháng 6, thời điểm này cả thời tiết và thiên nhiên đều rực rỡ và tươi mới nhất. Tại Jeju có sân bay quốc tế có thể bay thẳng từ Tokyo, Osaka, Bắc Kinh và Thượng Hải tới, đáp ứng nhu cầu khám phá Jeju của du khách của tế. Cảnh đẹp đảo Jeju chẳng lẽ không đủ sức hút níu chân hàng vạn du khách đến với Hàn Quốc hay sao?! Đảo Jeju có gì khiến khách du lịch mê mẩn? Cùng khám phá những điều này nhé!",
        tacgia:"intertour",
        bgimage:"https://intertour.vn/uploads/media/news/3526f38b-04c7-4c3e-a8df-0c2d9f4971c3.jpg",
        img1:"https://cdn.pixabay.com/photo/2020/05/05/07/52/republic-of-korea-5131925__340.jpg",
        img2:"https://cdn.pixabay.com/photo/2017/07/10/15/18/jeju-2490410__480.jpg",
        img3:"https://cdn.pixabay.com/photo/2021/08/09/11/38/island-6533073__480.jpg",
        img4:"https://cdn.pixabay.com/photo/2015/09/10/14/53/jeju-934530__480.jpg",
    },
    {
        id:'5',
        time:'3 hour',
        image:"https://media.vov.vn/uploaded/iks5biboyf0v5jhf2jbg/2016_04_10/anh4_wjns.jpg",
        name:"Vườn quốc gia Komodo",
        detail:"Vườn quốc gia Komodo là nơi duy nhất còn tồn tại loài thằn lằn khổng lồ và được UNESCO công nhận là di sản thế giới vào năm 1991.",
        post:"Vườn quốc gia Komodo là nơi duy nhất còn tồn tại loài thằn lằn khổng lồ và được UNESCO công nhận là di sản thế giới vào năm 1991.",
        noidung:"Vườn quốc gia Komodo tọa lạc tại khu vực thuộc quần đảo Nusa Tenggara của Indonesia, trên khu vực ranh giới giữa hai tỉnh Nusa Tenggara Timur và Nusa Tenggara Barat. Vườn quốc gia gồm 3 hòn đảo lớn là Komodo, Rinca và Pudar cùng vài hòn đảo nhỏ khác. Tổng diện tích vườn quốc gia là 1.817 km2.Năm 1980, vườn quốc gia này được thành lập với mục đích bảo vệ loài thằn lằn khổng lồ là rồng Komodo. Sau đó vườn được mở rộng mục đích là bảo tồn hệ thống thực vật nói chung, kể cả các loài sinh vật vùng biển, các hòn đảo cũng như động thực vật trên đảo. Đa số đảo của vườn quốc gia Komodo đều có nguồn gốc cũ là núi lửa.Rồng Komodo là loài thằn lằn nặng nhất và lớn nhất trong số những loài còn tồn tại trên Trái đất. Nó có thể dài tới hơn 3 mét, nặng 166 kg và là kẻ săn mồi kinh hoàng đối với nhiều con vật. Có những thông tin (nhưng chưa được kiểm chứng) rằng có loài rồng Komodo sống ở các khu rừng nhiệt đới phía bắc Australia với kích thước lớn gấp 3 lần rồng Komodo ở Indonesia, tức dài gần 10 m. Các nhà khoa học thì đã phát hiện những hóa thạch của loài rồng Komodo ở bang Queenland (Australia) và chúng được cho là đã biến mất cách đây 19.000 năm với kích thước lớn gấp 2 lần rồng komodo hiện nay đang sinh sống. Do rồng Komodo thuộc loài bò sát, hung dữ và rất nguy hiểm nên chúng không được thuần dưỡng như những loài động vật có vú ăn thịt khác.",
        tacgia:"khoahoc.tv",
        bgimage:"https://media.vov.vn/uploaded/iks5biboyf0v5jhf2jbg/2016_04_10/anh3_uzgx.jpg",
        img1:"https://cdn.pixabay.com/photo/2018/09/19/04/28/labuanbajo-3687809__340.jpg",
        img2:"https://cdn.pixabay.com/photo/2014/01/02/19/51/komodo-dragon-237805_1280.jpg",
        img3:"https://cdn.pixabay.com/photo/2016/03/16/20/21/landscape-1261626__340.jpg",
        img4:"https://cdn.pixabay.com/photo/2020/06/11/09/11/komodo-5285883__480.jpg",
    },
    {
        id:'6',
        time:'3 hour',
        image:"https://image.thanhnien.vn/w2048/Uploaded/2014/Pictures20118/VienAn/7KyQuanThienNhienTheGioi/SongNgamPuertoPrincesa.jpg",
        name:"Sông ngầm Puerto Princesa ",
        detail:"Sông ngầm Puerto Princesa (Philippines) là dòng chảy dưới một núi đá vôi, với chiều dài 8,2 km. Cảnh quan ở đây bao gồm những nhũ đá, măng đá và hang động. Đây được xem là sông ngầm dài nhất thế giới.",
        post:"Sông ngầm Puerto Princesa (Philippines) là dòng chảy dưới một núi đá vôi, với chiều dài 8,2 km. Cảnh quan ở đây bao gồm những nhũ đá, măng đá và hang động. Đây được xem là sông ngầm dài nhất thế giới.",
        noidung:"Đến Philippines, du khách sẽ không khỏi bị cuốn hút bởi hòn đảo Palawan, nơi có những bãi biển hoang sơ và dòng sông ngầm Puerto Princesa hiền hòa, xanh trong, lững lờ trôi, ẩn mình trong hang đá.Sông ngầm Puerto Princesa được công nhận là 1 trong 7 kỳ quan thiên nhiên thế giới mới, nằm trong vườn quốc gia sông ngầm Puerto Princesa. Đây được coi là thắng cảnh nổi tiếng nhất ở Philippines. Dưới đây là những điều đã tạo nên sự độc đáo của sông ngầm Puerto Princesa mà hiếm thấy một nơi nào có được. Dòng sông ngầm hiếm hoi này có dòng chảy trực tiếp ra biển sau khi chảy ngoằn ngoèo trong các động. Thủy triều ảnh hưởng đến mực nước ngầm với hơn 5km, nguồn nước lợ nằm ở phần dưới của sông do sự pha trộn giữa nước ngọt và nước mặn.Dòng sông ngầm dài 8km nằm dưới những hang đá vôi cực lớn, đầy những nhũ đá, măng đá hàng triệu năm tuổi. Muốn thám hiểm dòng sông ngầm này, du khách cần phải chèo thuyền vào sâu bên trong, qua những cửa hang tối, sâu hút. So với những dòng sông ngầm khác trên thế giới, Puerto Princesa là dòng sông ngầm dài thứ 2.",
        tacgia:"vyctravel",
        bgimage:"http://vyctravel.com/libs/upload/ckfinder/images/Song%20ngam%202.jpg",
        img1:"https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1295,h_720/w_80,x_15,y_15,g_south_west,l_klook_water/activities/lxonyeuu3jwtavzldwjp/[SALE]TourThamQuanS%C3%B4ngNg%E1%BA%A7mPuertoPrincesa.webp",
        img2:"https://phuotvivu.com/blog/wp-content/uploads/2018/07/vuon-quoc-gia-song-ngam-puerto-princesa.jpg",
        img3:"http://vyctravel.com/libs/upload/ckfinder/images/Song%20ngam%205.jpg",
        img4:"http://vyctravel.com/libs/upload/ckfinder/images/Song%20ngam%208.jpg",
        
    }
    ,
    {
        id:'7',
        time:'3 hour',
        image:"https://image.thanhnien.vn/w2048/Uploaded/2014/Pictures20118/VienAn/7KyQuanThienNhienTheGioi/NuiBan.jpg",
        name:"Núi Bàn ",
        detail:"Núi Bàn là một biểu tượng của Nam Phi, cao 1.086m so với mực nước biển. Đây cũng là địa danh tự nhiên duy nhất trên hành tinh này có một chòm sao được đặt tên theo nó là Mensa, nghĩa là “bàn”.",
        post:"Ngọn núi có đỉnh bằng phẳng đã trải qua 6 triệu năm xói mòn và tạo nên sự màu mỡ. Đây là vương quốc của những loài hoa nhỏ nhất trên trái đất với hơn 1.470 loài. Núi Bàn tự hào là nơi chứa nhiều loài động thực vật quý hiếm có nguy cơ tuyệt chủng.",
        noidung:"Nếu núi Phú Sỹ là biểu tượng của đất nước Nhật Bản thì núi Bàn được chọn là hình ảnh biểu tượng của Nam Phi.Núi có đỉnh bằng phẳng nên gọi là núi Bàn, nơi nhìn ra Cape Town và được chọn làm hình ảnh đặc trưng trên lá cờ của Cape Town và phù điêu khác của chính quyền địa phương.Núi là một phần của Vườn quốc gia núi Bàn Nam Phi. Đến nơi đây du khách có thể sử dụng cáp treo hoặc đi bộ đường dài lên núi.Chuyện kể rằng, năm 1503, một người châu Âu là thủy thủ người Bồ Đào Nha có tên là Antonio de Saldahan lần đầu tiên đặt chân đến vịnh này. Bấy giờ Nam Phi vẫn còn rất hoang vắng và chỉ là nơi cư ngụ của thổ dân địa phương KhoikhoiBất chợt trông thấy một dãy núi với hình dáng “lạ kỳ” nằm trong vịnh, Antonio de Saldahan chợt buột miệng thốt lên bằng tiếng Bồ Đào Nha : “Montanha da Mesa” mà theo tiếng Anh nó có nghĩa là “Table Mountain – Núi Đá Bàn”. Kể từ đó, cái tên “Table Mountain” hay “Núi Đá Bàn” được ra đời vào năm 1503 để đặt tên cho một ngọn núi, mà đỉnh của nó nhìn từ xa trông như một mặt bàn bằng phẳng. Và kể từ năm đó, cái tên vịnh “Table – cái bàn” cũng được ra đời để đặt tên cho vịnh ở nơi đây.Khía cạnh chính của núi Đá Bàn chính là một mặt bàn bằng phẳng có kích thước khoảng 3 km theo chiều dài và được bao bọc sung quanh bởi các vách đá thẳng đứng. Cấu tạo nên mặt bàn này bao gồm các dãy núi : đỉnh “Ác quỷ – Devil” ở phía đông, ngọn núi “đầu sư tử – Lion Head” ở phía tây. Nhìn một cách tổng thể về kiến trúc, núi Đá Bàn giống như một sân khấu với : đỉnh Devil và núi Lion Head là 2 bên cánh gà của sân khấu, trung tâm Cape Town và cảng “vịnh bàn – Table Bay” đóng vai trò là tấm màn sân khấu nằm phía sau sân khấu, “Đồi tín hiệu – Signal” cùng với thành phố Bowl phía trước là một thính phòng để khán giả ngồi xem trên sân khấu các diễn viên đang diễn một vở kịch.",
        tacgia:"vyctravel",
        bgimage:"https://dulichkhatvongviet.com/wp-content/uploads/2014/03/nui-da-ban.jpg",
        img1:"https://wiki-travel.com.vn/Uploads/Picture/summer-180902030927-nam-phi-nui-ban.jpg",
        img2:"https://vcdn-vnexpress.vnecdn.net/2018/10/09/nui-Ban-7306-1539060824.jpg",
        img3:"https://lh3.googleusercontent.com/proxy/mwbI4JZdCOieIr_R-zoOC30gdtvPzu6yyzfemuyjtsa0uR3scWDpce0w909_Rb1ceascyvbbhXCYTEAORJv7Mj3uVFef",
        img4:"https://todata.vn/view/at_nui-ban-bieu-tuong-cua-nam-phi_cnid-795_3194e9db22923710d4fe2cfcdf3ce408.jpg",
        
    }
    
    
]}